const workouts=[
["Day 1", "Beginner Full Body A", [["Machine Chest Press", "2 × 8–10", "75–90 sec"], ["Lat Pulldown", "2 × 8–10", "75–90 sec"], ["Seated Cable Row", "2 × 8–10", "75–90 sec"], ["Leg Press", "2 × 10", "90 sec"], ["Machine Shoulder Press", "2 × 8–10", "75–90 sec"], ["Rope Triceps Pushdown", "2 × 10–12", "60 sec"], ["Dumbbell Curl", "2 × 10–12", "60 sec"]]],
["Day 2", "Recovery", [["Walking", "6,000–8,000 steps + 5–10 min mobility", "—"]]],
["Day 3", "Beginner Full Body B", [["Leg Press", "2 × 10", "90 sec"], ["Goblet Squat", "2 × 8–10", "90 sec"], ["Seated Leg Curl", "2 × 10–12", "75 sec"], ["Leg Extension", "2 × 10–12", "75 sec"], ["Standing Calf Raise", "2 × 12–15", "60 sec"], ["Cable Crunch", "2 × 10–12", "60 sec"]]],
["Day 4", "Recovery", [["Walking", "6,000–8,000 steps", "—"]]],
["Day 5", "Beginner Full Body C", [["Machine Chest Press", "2 × 10", "75–90 sec"], ["Lat Pulldown", "2 × 10", "75–90 sec"], ["Leg Press", "2 × 10", "90 sec"], ["Seated Cable Row", "2 × 10", "75–90 sec"], ["Dumbbell Lateral Raise", "2 × 12", "60 sec"], ["Rope Triceps Pushdown", "2 × 12", "60 sec"], ["Hammer Curl", "2 × 12", "60 sec"]]],
["Day 6", "Easy Cardio", [["Easy treadmill/cycle", "15–20 min + 6,000–8,000 steps", "—"]]],
["Day 7", "Rest", [["Rest / optional easy walk", "Recovery", "—"]]],
["Day 8", "Beginner Full Body A", [["Machine Chest Press", "2 × 8–10", "75–90 sec"], ["Lat Pulldown", "2 × 8–10", "75–90 sec"], ["Seated Cable Row", "2 × 8–10", "75–90 sec"], ["Leg Press", "2 × 10", "90 sec"], ["Machine Shoulder Press", "2 × 8–10", "75–90 sec"], ["Rope Triceps Pushdown", "2 × 10–12", "60 sec"], ["Dumbbell Curl", "2 × 10–12", "60 sec"]]],
["Day 9", "Recovery", [["Walking", "7,000–8,500 steps", "—"]]],
["Day 10", "Beginner Full Body B", [["Leg Press", "2 × 10", "90 sec"], ["Goblet Squat", "2 × 8–10", "90 sec"], ["Seated Leg Curl", "2 × 10–12", "75 sec"], ["Leg Extension", "2 × 10–12", "75 sec"], ["Standing Calf Raise", "2 × 12–15", "60 sec"], ["Cable Crunch", "2 × 10–12", "60 sec"]]],
["Day 11", "Recovery", [["Walking", "7,000–8,500 steps", "—"]]],
["Day 12", "Beginner Full Body C", [["Machine Chest Press", "2 × 10", "75–90 sec"], ["Lat Pulldown", "2 × 10", "75–90 sec"], ["Leg Press", "2 × 10", "90 sec"], ["Seated Cable Row", "2 × 10", "75–90 sec"], ["Dumbbell Lateral Raise", "2 × 12", "60 sec"], ["Rope Triceps Pushdown", "2 × 12", "60 sec"], ["Hammer Curl", "2 × 12", "60 sec"]]],
["Day 13", "Easy Cardio", [["Easy treadmill/cycle", "20 min + 7,000–8,500 steps", "—"]]],
["Day 14", "Rest", [["Rest / optional easy walk", "Recovery", "—"]]],
["Day 15", "Upper A", [["Machine Chest Press", "3 × 8–12", "90 sec"], ["Lat Pulldown", "3 × 8–12", "90 sec"], ["Seated Cable Row", "3 × 8–12", "90 sec"], ["Machine Shoulder Press", "2 × 10–12", "75 sec"], ["Rope Triceps Pushdown", "2 × 10–15", "60 sec"], ["Dumbbell Curl", "2 × 10–15", "60 sec"]]],
["Day 16", "Lower A", [["Leg Press", "3 × 8–12", "120 sec"], ["Goblet Squat", "2 × 10", "90 sec"], ["Seated Leg Curl", "3 × 10–15", "75 sec"], ["Leg Extension", "2 × 10–15", "75 sec"], ["Calf Raise", "3 × 12–15", "60 sec"], ["Cable Crunch", "3 × 10–15", "60 sec"]]],
["Day 17", "Recovery", [["Walking + mobility", "8,000 steps + mobility", "—"]]],
["Day 18", "Upper B", [["Incline Machine Press", "3 × 8–12", "90 sec"], ["Lat Pulldown", "3 × 8–12", "90 sec"], ["One-arm Cable Row", "2 × 10–12/side", "75–90 sec"], ["Dumbbell Lateral Raise", "3 × 12–15", "60 sec"], ["Face Pull", "2 × 12–15", "60 sec"], ["Hammer Curl", "2 × 10–15", "60 sec"], ["Rope Pushdown", "2 × 10–15", "60 sec"]]],
["Day 19", "Recovery", [["Walking", "8,000 steps", "—"]]],
["Day 20", "Lower B", [["Hack Squat / Leg Press", "3 × 8–12", "120 sec"], ["Hip Thrust Machine / Bench", "3 × 10–12", "90 sec"], ["Seated Leg Curl", "3 × 10–15", "75 sec"], ["Leg Extension", "2 × 10–15", "75 sec"], ["Calf Raise", "3 × 12–15", "60 sec"], ["Knee Raise / Captain’s Chair", "2 × 8–12", "60 sec"]]],
["Day 21", "Rest", [["Rest / optional easy walk", "Recovery", "—"]]],
["Day 22", "Upper A", [["Machine Chest Press", "3 × 8–12", "90 sec"], ["Lat Pulldown", "3 × 8–12", "90 sec"], ["Seated Cable Row", "3 × 8–12", "90 sec"], ["Machine Shoulder Press", "2 × 10–12", "75 sec"], ["Rope Triceps Pushdown", "2 × 10–15", "60 sec"], ["Dumbbell Curl", "2 × 10–15", "60 sec"]]],
["Day 23", "Lower A", [["Leg Press", "3 × 8–12", "120 sec"], ["Goblet Squat", "2 × 10", "90 sec"], ["Seated Leg Curl", "3 × 10–15", "75 sec"], ["Leg Extension", "2 × 10–15", "75 sec"], ["Calf Raise", "3 × 12–15", "60 sec"], ["Cable Crunch", "3 × 10–15", "60 sec"]]],
["Day 24", "Recovery", [["Walking", "8,000–9,000 steps", "—"]]],
["Day 25", "Upper B", [["Incline Machine Press", "3 × 8–12", "90 sec"], ["Lat Pulldown", "3 × 8–12", "90 sec"], ["One-arm Cable Row", "2 × 10–12/side", "75–90 sec"], ["Dumbbell Lateral Raise", "3 × 12–15", "60 sec"], ["Face Pull", "2 × 12–15", "60 sec"], ["Hammer Curl", "2 × 10–15", "60 sec"], ["Rope Pushdown", "2 × 10–15", "60 sec"]]],
["Day 26", "Lower B", [["Hack Squat / Leg Press", "3 × 8–12", "120 sec"], ["Hip Thrust Machine / Bench", "3 × 10–12", "90 sec"], ["Seated Leg Curl", "3 × 10–15", "75 sec"], ["Leg Extension", "2 × 10–15", "75 sec"], ["Calf Raise", "3 × 12–15", "60 sec"], ["Knee Raise / Captain’s Chair", "2 × 8–12", "60 sec"]]],
["Day 27", "Easy Cardio", [["Easy incline walk/cycle", "25 min + 8,000–9,000 steps", "—"]]],
["Day 28", "Rest", [["Full recovery", "Recovery", "—"]]],
["Day 29", "Upper A Check", [["Machine Chest Press", "3 × 8–12", "90 sec"], ["Lat Pulldown", "3 × 8–12", "90 sec"], ["Seated Cable Row", "3 × 8–12", "90 sec"], ["Machine Shoulder Press", "2 × 10–12", "75 sec"], ["Rope Triceps Pushdown", "2 × 10–15", "60 sec"], ["Dumbbell Curl", "2 × 10–15", "60 sec"]]],
["Day 30", "Lower A Check", [["Leg Press", "3 × 8–12", "120 sec"], ["Goblet Squat", "2 × 10", "90 sec"], ["Seated Leg Curl", "3 × 10–15", "75 sec"], ["Leg Extension", "2 × 10–15", "75 sec"], ["Calf Raise", "3 × 12–15", "60 sec"], ["Cable Crunch", "3 × 10–15", "60 sec"]]],
];
const allWorkoutDays=workouts;
const meals={
'Breakfast':[['B1','60 g oats + 250 ml milk + 200 g Greek/hung curd + chia','~450 kcal','~30 g'],['B2','2 moong-dal chillas + 150 g curd + vegetables','~400 kcal','~25 g'],['B3','2 besan chillas + 100 g tofu stuffing + curd','~450 kcal','~28 g'],['B4','Vegetable oats upma + 150 g tofu','~430 kcal','~25 g'],['B5','2 rotis + tofu/paneer bhurji + curd','~450 kcal','~28 g']],
'Mid-Morning':[['S1','200 g Greek/hung curd','~140 kcal','~18 g'],['S2','40 g roasted chana + buttermilk','~200 kcal','~11 g'],['S3','Sprouts chaat + 100 g curd','~200 kcal','~13 g'],['S4','150 g tofu + cucumber','~180 kcal','~18 g'],['S5','Milk + fruit','~180 kcal','~9 g']],
'Lunch':[['L1','2 rotis + dal + 150 g tofu + vegetables + salad','~550 kcal','~35 g'],['L2','1 cup rice + rajma + 150 g tofu + salad','~550 kcal','~30 g'],['L3','2 rotis + chole + 150 g low-fat paneer + vegetables','~600 kcal','~35 g'],['L4','1 cup rice + moong dal + tofu + vegetables','~500 kcal','~30 g'],['L5','2 rotis + soy-chunk curry + vegetables + curd','~550 kcal','~38 g']],
'Evening':[['E1','Roasted chana + buttermilk','~200 kcal','~11 g'],['E2','Greek/hung curd + fruit','~200 kcal','~18 g'],['E3','Sprouts chaat','~180 kcal','~12 g'],['E4','Tofu + vegetables','~180 kcal','~18 g'],['E5','Low-fat paneer + cucumber','~200 kcal','~20 g']],
'Dinner':[['D1','Soy chunks + 1–2 rotis + vegetables + curd','~450 kcal','~35 g'],['D2','Tofu bhurji + 2 rotis + salad','~450 kcal','~30 g'],['D3','Low-fat paneer + 1–2 rotis + vegetables','~500 kcal','~32 g'],['D4','Soy curry + rice + vegetables','~450 kcal','~30 g'],['D5','Tofu + dal + 1 roti + vegetables','~450 kcal','~35 g']],
'Pre-Workout':[['P1','Banana + black coffee','~120 kcal','~1 g'],['P2','Banana + 2 dates','~150 kcal','~1 g'],['P3','Apple + black coffee','~100 kcal','~0 g'],['P4','Banana + 1 slice whole-wheat toast','~180 kcal','~3 g']],
'Post-Workout':[['PW1','250 ml toned milk + fruit','~200 kcal','~10 g'],['PW2','200 g Greek/hung curd + fruit','~200 kcal','~18 g'],['PW3','Oats + milk + curd','~400 kcal','~25–30 g'],['PW4','150 g tofu + fruit','~220 kcal','~18 g']]
};
function key(i,j){return `wd-${i}-${j}`}
function renderWorkouts(){const root=document.getElementById('workoutGrid');root.innerHTML=allWorkoutDays.map((d,i)=>`<article class="day-card" id="day-${i}"><div class="day-title"><div><h3>${d[0]}</h3><div class="focus">${d[1]}</div></div><span class="small">${d[2].length} items</span></div>${d[2].map((e,j)=>{const k=key(i,j);const checked=localStorage.getItem(k)==='1';return `<label class="exercise"><input type="checkbox" data-k="${k}" ${checked?'checked':''}><span class="name">${e[0]}</span><span class="meta">${e[1]}</span><span class="meta">${e[2]}</span></label>`}).join('')}</article>`).join('');root.querySelectorAll('input[type=checkbox]').forEach(cb=>cb.addEventListener('change',()=>{localStorage.setItem(cb.dataset.k,cb.checked?'1':'0');updateWorkoutProgress()}));updateWorkoutProgress()}
function updateWorkoutProgress(){let boxes=[...document.querySelectorAll('#workoutGrid input')];let done=boxes.filter(x=>x.checked).length;let pct=boxes.length?done/boxes.length*100:0;document.getElementById('workoutBar').style.width=pct+'%';document.getElementById('workoutProgressText').textContent=`${done} of ${boxes.length} exercises completed (${Math.round(pct)}%)`;document.querySelectorAll('.day-card').forEach(c=>c.classList.toggle('done',[...c.querySelectorAll('input')].every(x=>x.checked)))}
function renderMeals(){const root=document.getElementById('mealGrid');root.innerHTML=Object.entries(meals).map(([type,opts])=>`<article class="meal-card"><div class="meal-type">${type}</div>${opts.map(o=>`<div class="meal-row"><div><strong>${o[0]}</strong><br>${o[1]}</div><div>${o[2]}<br><strong>${o[3]}</strong></div></div>`).join('')}</article>`).join('')}
function getProgress(){return JSON.parse(localStorage.getItem('fit-progress')||'[]')}
function renderProgress(){let rows=getProgress().sort((a,b)=>a.date.localeCompare(b.date));document.getElementById('progressRows').innerHTML=rows.map(r=>`<tr><td>${r.date}</td><td>${r.weight||'—'}</td><td>${r.waist||'—'}</td><td>${r.steps||'—'}</td><td>${r.calories||'—'}</td><td>${r.protein||'—'}</td></tr>`).join('');let weights=rows.map(r=>+r.weight).filter(Boolean);let latest=weights.at(-1), first=weights[0], loss=latest&&first?(first-latest).toFixed(1):'—';let avg=weights.length? (weights.slice(-7).reduce((a,b)=>a+b,0)/Math.min(7,weights.length)).toFixed(1):'—';document.getElementById('progressCards').innerHTML=`<div class="metric"><div class="v">${latest??'—'}</div><div class="l">Latest weight (kg)</div></div><div class="metric"><div class="v">${avg}</div><div class="l">Recent average (kg)</div></div><div class="metric"><div class="v">${loss}</div><div class="l">Change since first (kg)</div></div><div class="metric"><div class="v">${rows.length}</div><div class="l">Entries logged</div></div>`}
document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.getElementById(t.dataset.tab).classList.add('active')}));
document.getElementById('resetWorkout').onclick=()=>{if(confirm('Reset all workout check marks?')){Object.keys(localStorage).filter(k=>k.startsWith('wd-')).forEach(k=>localStorage.removeItem(k));renderWorkouts()}};
document.getElementById('addProgress').onclick=()=>{let entry={date:document.getElementById('pDate').value,weight:document.getElementById('pWeight').value,waist:document.getElementById('pWaist').value,steps:document.getElementById('pSteps').value,calories:document.getElementById('pCalories').value,protein:document.getElementById('pProtein').value};if(!entry.date){alert('Please select a date.');return}let rows=getProgress().filter(r=>r.date!==entry.date);rows.push(entry);localStorage.setItem('fit-progress',JSON.stringify(rows));renderProgress()};
document.getElementById('clearProgress').onclick=()=>{if(confirm('Clear all progress entries?')){localStorage.removeItem('fit-progress');renderProgress()}};
document.getElementById('pDate').value=new Date().toISOString().slice(0,10);renderWorkouts();renderMeals();renderProgress();
